### ISSUE TITLE
IndexError: index 1 is out of bounds for axis 1 with size 1

### ISSUE THREAD

**Issue by waylongo** [physionetchallenges/python-example-2023#3]
https://github.com/physionetchallenges/python-example-2023/blob/f1658b4f98f28adf14f4c6d6baf49f035a939f93/team_code.py#L120

Should
`outcome_probability = outcome_model.predict_proba(features)[0, 1]`
be 
`outcome_probability = outcome_model.predict_proba(features)[0]`
?

**Comment by matthewreyna** [comment]
Thank you for sharing this error, and I am sorry that you experienced it.

Unfortunately, I cannot reproduce this error. The suggested change would create an error on my machine.

Can you please verify that you are running the commands in the README of this repository, including in Docker? If not, then can you please share the commands that you are running and the versions of the libraries, especially the scikit-learn library, that you are using? The example code uses version 1.1.3 of scikit-learn, but the code also runs in the (currently) latest version 1.2.1 of scikit-learn.

We would like for this code to work as generally as possible, but it may work differently or not at all on some versions of some libraries or packages, which change over time.

**Comment by waylongo** [comment]
I have not yet used Docker in the project. I used exact command in the repo.
My scikit-learn version is 1.0.2, maybe this is the issue.

**Comment by matthewreyna** [comment]
Unfortunately, I am unable to reproduce your error or any error with scikit-learn version 1.0.2.

I recommend trying the same versions of the packages that we indicated in the `requirements.txt` file in the example code. You can use a lightweight virtual environment like [venv](https://docs.python.org/3/library/venv.html) or a Docker environment to do so. We ask that teams describe their environment in a Dockerfile and test their code in Docker before submitting it so that we can reproduce as much of their local environment as possible and avoid these crashes.

**Comment by waylongo** [comment]
Well, I created a new virtual environment in conda. Installed all packages in requirements.txt. But still, I got the same error. 
The "predict_proba" function should return one value, but here [0, 1] returns two values. That does not make sense to me.
Anyway, changing [0, 1] to [0] works for me.
